# Generated by Django 5.0.4 on 2024-04-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
