# Generated by Django 5.0.4 on 2024-04-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node1', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('med_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=20)),
                ('medications', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20)),
                ('medications', models.TextField()),
                ('lab_tests', models.TextField()),
                ('dosage_instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
